kind: pipeline
type: kubernetes
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
      repo: tobru/pylokid
      auto_tag: true
